### ISSUE TITLE
Result for training more than 100k

### ISSUE THREAD

**Issue by merv22** [ac-93/soft-actor-critic#3]
Hi.
I was wondering that have you done training for more time steps than 100k or with other hyper-parameters?
Unfortunately I don't have a GPU yet so I can not do experiments myself.
The reports in the paper "SOFT ACTOR-CRITIC FOR DISCRETE ACTION SETTINGS" are for 100k training steps, but does the algorithm learns for example the Pong game, if trained for for steps?

Thanks

**Comment by ac-93** [comment]
Hi, 

Sorry it's been a while since I've done any work with discrete SAC so I don't have too much info to offer. From memory the results tended to converge after 100k steps, at least with default parameters. That's not to say that it couldn't continue to learn with better hyper-params/more tuning though. 

@yining043 took this implementation a little further and did some additional experiments, maybe he has more insight to offer? 

Poking around his [repo](https://github.com/yining043/SAC-discrete) it seems that pong was one of the environments that this algorithm struggled to learn anything useful with.

**Comment by merv22** [comment]
Thank for the quick reply.

It seems that breakout was another environment for which the paper states negative results, but based on your results and @yining043 repo, SACD can learn in that environment, which is good news overall. Pong is a strange case however !

Thanks again.

**Comment by ac-93** [comment]
No worries. There's probably some implementation details that can account for differences in results. Let me know if you find out any more info on SACD performance!

**Comment by merv22** [comment]
OK. Thanks.
